### ISSUE TITLE
Interface scrambled since 0.0.6

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#10]
The interface seems to be botched since the 0.0.6 release, not sure what happened here. Thought I'd let you know.

![test](https://user-images.githubusercontent.com/24809863/38270945-44672650-3785-11e8-93fd-bbdb1f7685d6.png)

Running the tests tries to expand the view to make it larger and larger, but it does not add a scrollbar, so the test output eventually fills the entire dock.

This seems to happen with all themes.

**Comment by twifty** [comment]
I just pushed 0.0.7, does the same happen there?

**Comment by Gert-dev** [comment]
Just tried updating, but the same still seems to happen. Very strange. Also tried One Dark again to be sure, but the same happens there.

**Comment by twifty** [comment]
Hmm, I switched out the `xterm` for my own implementation in 0.0.6. I can't quite see from the image if it is the terminal or not which is causing the problems.

**Comment by twifty** [comment]
I cannot reproduce this. I've tried large test projects (symfony/framework-bundle) and a number of themes. I even tried extra long command lines in the terminal. This is making me think it is platform dependent. Which version of atom are you using and on which OS?

**Comment by twifty** [comment]
Try 0.0.8. In 0.0.6 I moved all the etch components to their own npm package, but I forgot to import the stylesheet.

For some reason, my system has been rendering without a problem. Atom must have cached that stylesheet somewhere.

**Comment by Gert-dev** [comment]
That seems to have fixed it, thanks.
