### ISSUE TITLE
Little bit of styling/usability feedback

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#11]
The visual appearance of this package has already much improved since the first version, in my opinion. Design and usability isn't my expertise, but I thought I'd bounce some things I've noticed off of you, so you can decide if you want to fix them or not :smile:.

* Add title attributes to the action buttons, e.g. `title="Run tests"` in their HTML, so that hovering over the buttons shows what they do
* The mentioning of the status after the test name, such as `passed` feels a bit redundant, as the icon already provides a (better) indicator of this; removing it would reduce clutter in the tests tree (optionally, you could also try adding `title` attributes to the status icons)
* I'd use another color for the amount of time a test took. Using the "passed" color (usually green) really draws your eyes to the time, whilst in most cases it is just a minor detail - I do agree showing the time is useful, however, to track down slow tests. Perhaps a good color may be a somewhat darker or less apparent or "phased out" version of the color used for the test name.
  * Alternatively, you could move it to a second column or inside the expando for each test. The expando would move it out of sight, but makes you lose the ability to get a quick overview. Using a second column, on the other hand, would allow sorting by it.
* I'd replace colors with the colors defined by classes specified in the [atom styleguide package](https://atom.io/packages/styleguide), e.g. `<div class='text-success'>Success text</div>`. Theme authors use the styleguide to theme everything in Atom and using these colors helps ensure the package looks visually appealing in even the most exuberant of themes.
  * There is also a list of default icons in Atom in there (octicons). Using these for the action buttons as well as in the tests tree (passed/failed/skipped) would also improve the visual appeal.
* Show a progress/busy indicator - there is one in the styleguide - over the tests tree whilst PHPUnit is still running
* I seem to be able to type inside the raw tests output, though the fact that I can select and copy output is extremely useful - if it is impossible to fix without removing that ability, I'd just leave it :smile: .
* The down arrow in the suite selection dropdown seems to overlap the text inside it: ![example](https://user-images.githubusercontent.com/24809863/38318448-a25ead5a-382f-11e8-927a-3ab5401d0d3e.png)

**Comment by twifty** [comment]
* Title attributes is an easy fix, I'll push that into the next version
* The status after the result is a byproduct of trying to mimic the netbeans environment. I agree it has become redundant with the icons. With button attributes, I could probably remove that clutter.
* I'll play around with the test time. Perhaps floating it to the right with a more faded text colour would work.
* The icon colors are already set according to the text colours of the theme. Though I admit they are a little too 'in your face'. I'll see if I can fade them a little.
* A progress indicator is a big change, and something I saw the need for yesterday. I want to also implement a method of cancelling tests. The problem with the progress is it requires parsing the raw stdout, which ties it to phpunit and adds to the complexity. But, it is needed.
* The terminal contains a text input required for sending stdin data to the running process. It's not used in this package, but my other `symfony-commands` package uses it for those interactive commands. I'll see about making it hidden when a test has completed, or even adding an option to the component to disable stdin.
* Does that down arrow occur with other themes? That particular control is styled according to the theme. I'll take a look and see if it's something I can fix on my end.

**Comment by twifty** [comment]
All suggestions implemented in 0.0.10

The styling of the select list appears to be a problem in your theme. Does the same problem occur in the styleguide? If so I suggest reporting it to the theme author.

**Comment by Gert-dev** [comment]
It is indeed an issue in my theme. I've reported it to the theme author.
