### ISSUE TITLE
Output console grabs focus as output is being appended

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#12]
It seems the PHPUnit output console (with the raw output) grabs the keyboard cursor everytime it is updated. If your test suite is slowly running and dots appear every so often, typing becomes nigh impossible.

**Comment by twifty** [comment]
As mentioned in #11, The terminal grabs focus during a process's stdout for those instances when a process requires stdin. stdin is not required by phpunit or any other test runner I can think of. I'll see about disabling it for this package.
