### ISSUE TITLE
Allow adding additional parameters to command line of PHPUnit

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#16]
This can be handy in some cases, such as when using `paratest`, in which case you would add the amount of processes that may be spawned simultaneously via the `-j<count>` argument (e.g. `-j5`).

**Comment by twifty** [comment]
I'll add this as a package option. I'm wondering though is this something you would change often. If so I might have to make it configurable from the view.

**Comment by Gert-dev** [comment]
Thanks. This would indeed not be something you change often, at least not in the case of the jobs option. What might be changed more often, and this is likely why the tester package does add it inside the view, is the `--filter` parameter's value, but its use seems unnecessary as php-unit-integrator already supports running single tests.
