### ISSUE TITLE
"Filter Failures" and "Filter Passed" don't seem to have any effect on (merged) tests tree

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#18]
In 0.0.17 neither of these buttons seems to have any effect on the tests tree anymore. I can still find my failed tests manually, though.

Might it also be a good idea to (provide the ability to) sort failed tests on top? That way failures always jump into your immediate view without having to click the button.

**Comment by twifty** [comment]
Confirmed. I wonder what I broke this time?

**Comment by Gert-dev** [comment]
Heh, it may be interesting to write some specs/tests for these :-).

**Comment by twifty** [comment]
I can write tests in PHP with ease, but testing with something like `mocha` on a GUI like this makes my head hurt. Suppose I have to learn sometime though...

**Comment by Gert-dev** [comment]
Tell me about it. I have everyone believing I'm rewriting PHP Integrator's CoffeeScript packages in PHP to move towards becoming an LSP in the future, but secretly I just don't like JavaScript :wink:.

**Comment by twifty** [comment]
Fixed in 0.0.18

Note to self, don't depend on `etch.update` to update elements! It completely ignores any attributes applied and excludes the element from its `patch` as being the same.
