### ISSUE TITLE
Icons of buttons in the dock don't show up

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#3]
It seems the icons of the buttons in the dock don't show up for me. Perhaps this has something to do with the fact that they appear to be icon fonts. I'm using the nebula theme, but using a default Atom theme, such as One Dark, yields no improvement.

Screenshot of the behavior:

![example](https://user-images.githubusercontent.com/24809863/38147883-6e8afc88-3454-11e8-888a-28d1d5ae52ab.png)

Perhaps you could replace the custom font or icon fonts with standard Atom icons. If you open the Atom styleguide (it is a default Atom package), there should be a list of available octicons that are available for use in packages.

**Comment by twifty** [comment]
The font icons use font-awesome, which is included in the package. This is most definitely a bug.
