### ISSUE TITLE
Run test case broken

### ISSUE THREAD

**Issue by twifty** [twifty/atom-phpunit-integrator#32]
Selecting a test case within the tree and clicking 'run selected' is broken, AGAIN!

**Comment by Gert-dev** [comment]
Heh, I was just wondering what that "Run selected" button was supposed to do, as it doesn't seem to light up ;-).

**Comment by twifty** [comment]
I have it working in my local branch, just fiddling with the stylesheet before I push it.

If you ctrl-click items in the tree, the button will enable, allowing you to run selected classes/cases.

Another change I have implemented locally is alt-click for the expansion/collapse of the expandos. Previously, selecting them, which will update the console for batch tests, would also expand them.
