### ISSUE TITLE
Idea - Auto-expand failed test output

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#34]
This idea comes from the fact that, when one of my tests fail and I'm making modifications, I find myself constantly re-expanding the failed test output, sometimes to discover that I didn't actually fix the original issue, and sometimes to find that a new issue popped up. With a quick test-modify-test cycle, expanding in the tree every time quickly becomes a nuisance.

This may be a bit controversial, as the tree will expand in size rather quickly if this happens if there are many failing tests _or_ there is just a lot of output from the failed test. Perhaps a setting for it may be appropriate.

To avoid large test output quickly making the tree large, you could also limit the height of the tree and show a "Show more" / "Show less" button to lift/reapply the height limitation.

**Comment by twifty** [comment]
I was going to implement a collapse all by default. Now you mention expanding the failures, I can see that being very useful, especially now that failures are at the top. A line limit also sounds like a good feature. I could take this a step further and auto populate the console with the output of the error test (when using the test multiple files/classes feature that is).

**Comment by twifty** [comment]
I've implemented a quick fix in 0.0.29. Everything is expanded by default. I'll first fix the cursor bug then jump on this issue.

**Comment by twifty** [comment]
Implemented in 0.0.30

Default line count is 10 (configurable), with a 'More...' link on the last line. There is no point adding a 'Less' since it's already contained within an expando. Errors and Warnings always expand, everything else collapses by default.
