### ISSUE TITLE
Failed test output that is too wide becomes unreachable

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#39]
It appears that failed test output that is rather wide is currently unreachable; scrolling horizontally does not appear to work.

Either scrolling or soft wrapping should probably do the trick :-).

**Comment by Gert-dev** [comment]
Hmm, I forget to mention this is in the tests tree, not in the console. I do recall horizontal scrolling working in the tests tree as well, but it must have been broken somewhere more recently.

**Comment by twifty** [comment]
Ahh, That makes sense. Horizontal scrolling on that component will be a challenge due to the layout of the titles and times. Anything I do will have to be applied to the error text itself and not the tree as a whole.

I'll play with it later and see what I can come up with.
