### ISSUE TITLE
TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#42]
Since 0.0.44, whenever I run tests, the following error pops up:

```
 TypeError: Cannot read property 'setAttribute' of undefined
        at /home/werk/.atom/packages/php-unit-integrator/lib/views/php-unit-integrator-view.js:452:45
        at ViewRegistry.performDocumentUpdate (/usr/lib/atom/src/view-registry.js:238:7)
```

Not sure where it's coming from.

**Comment by twifty** [comment]
When you get this error, is the code coverage toggle visible? Judging by the line number (if it's correct) the code is setting the disabled attribute on the toggle, but it cannot find it. A bug for sure since now it's not rendered when XDebug is not available.

**Comment by Gert-dev** [comment]
The code coverage toggle is indeed not (yet) visible at that time, neither is the debug toggle.
