### ISSUE TITLE
Debug and code coverage toggle seems to have disappeared

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#45]
Not sure how or why this happened, but in the latest releases, I think around 0.0.47 or 0.0.48, these both seem to have disappeared. I have xdebug disabled in `php.ini` but have configured `xdebug.so` via the package settings.

**Comment by twifty** [comment]
I removed the debug toggle, but the coverage toggle should still show up. Have you correctly configured the path? And does the path contain the 'xdebug' substring?

**Comment by Gert-dev** [comment]
That seems indeed to be it. When this was first added, I just dumped `xdebug.so` in the xdebug path and that somehow worked. I've now put in the full path, and that seems to make it work again. Thanks!

**Comment by twifty** [comment]
Haha, I forced the full path since I'm not sure how other OS's handle just the extension name. The docs are a bit vague.
