### ISSUE TITLE
Allow running all test suites in project

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#5]
When a project contains multiple test ruites, such as, coincidentally, PHP Integrator's core, you can only run one suite at a time. It would be handy to be able to run all suites in one run, such as phpunit does by default.

I assume, but may be wrong in, that this also causes code coverage information to not be complete, as it only shows the sole test suite that ran.

**Comment by twifty** [comment]
I could add a new options 'all suites' to the choice list. Regarding coverage, if all suites are passed to phpunit, it could takes minutes to complete for large projects. A better method would be to run each suite in series and update the views accordingly. Such a change would require an overhaul of the current code.

I'll add it to the todo list. In the meantime, a new `testsuite` entry can be added to phpunit.xml which includes all directories/files.

**Comment by Gert-dev** [comment]
That indeed sounds like a good approach.

In any case, the integration of code coverage into the editor views is very much a step forward for Atom's PHP integration and lifts Atom towards a higher level of tool integration, IMO. It already surpasses what I had hoped [tester](https://github.com/yacut/tester) and [tester-phpunit](https://github.com/recca0120/tester-phpunit) would become.

An interesting idea to consider may be to split the PHPUnit logic from the actual implementation, so other testing tools could integrate into Atom as well, also supporting the same coverage. Not a feature request, but sometimes thinking big can lead to big results :wink: .

**Comment by twifty** [comment]
Implemented in 42f5820
