### ISSUE TITLE
"Go To Testcase" appears to not function

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#6]
This may be due to a setup issue on my side, but this context menu item appears to have no effect. It is available as option when right-clicking a test in the tests tree.

It would also be neat if this same behavior was achieved when a test in the tree is double-clicked (i.e. without having to right-click it first). Perhaps this is already the case, but I can't know for sure since the context menu isn't currently working for me either, so I thought I'd mention it anyways.

Also, a `cursor: pointer` style for the tests in the tests tree may be handy to indicate the available interaction (collapse/expand/open).

**Comment by twifty** [comment]
Where do you store your test cases in relation to your SUT files? How do you change the namespace for such files? Does the test class exist? If not does a modal window appear asking you to create it?

The current implementation tries to store new test files in a `tests` directory alongside the `src` directory. It also tries to inject 'Test' into the namespace for that directory. I realize this isn't the case for all users and plan to add the ability for the user to alter this behavior by adding a `phpunit.js` file anywhere in the hierarchy.

**Comment by twifty** [comment]
Completely missed the "in the tree" part of that report. Just spent two hours trying to figure out why the context menu in the source code view wasn't working :-(

Anyway, fixed and I'll implement the suggested changes.

**Comment by twifty** [comment]
Double click has been added to tree item, though it does delay single click to expand a little. Cursors have been added for expand/collapse and ctrl+click to select
