### ISSUE TITLE
Ability to generate code coverage seems to have disappeared

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#61]
This also seems to be the case in one of the latest releases. I have the path to XDebug configured in the settings panel (and set to `/usr/lib/php/modules/xdebug.so`), but no buttons show up to generate it, for some reason.

Let me know if you need any additional info.

**Comment by twifty** [comment]
The PHP extensions are now configured under the "Packages -> Settings View -> Shared" options.

Yesterday, I noticed within my local install that the extension setting remained within the `php-unit-integrator` package settings. If this is true for you, manually remove the extraneous entry from your `~/.atom./config.cson`. For some reason, atom adds it to the view even though it is no longer in the schema.

I will create an npm module to blitz these extraneous settings. It may come in useful when we rename/remove/relocate config keys.

**Comment by Gert-dev** [comment]
That was indeed it.

I don't like how Atom magically keeps around properties that have been removed from packages in updates. It was still being displayed as if it was a real property used by this package, whilst it has already disappeared in an update. It only disappear when you manually clear the field or remove it from your config file manually.

I guess it helps in not losing any data, but on the other hand, if the package doesn't use it anymore, you likely won't need it either. No sane package author renames settings that may contain large amounts of data just for fun either - at least, I hope not.

**Comment by twifty** [comment]
It is indeed annoying. Especially when a package is still in a beta state.

I intend to create a module to handle this problem. If we pass a callback, then all settings will be evaluated against the current schema. If any are extraneous, the provided callback can either migrate the value or remove it entirely. It shouldn't be difficult to create, but I'm a bit swamped with work ATM.
