### ISSUE TITLE
Failed tests get an expando, but nothing expands

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#7]
When one of my tests fails, it gets an expando to the left of it for some reason:

![failed test](https://user-images.githubusercontent.com/24809863/38148231-113d240c-3445-11e8-815b-df94c5681dbc.png)

I thought the actual failed assertions may be hidden behind it, but clicking it doesn't seem to expand anything. I also can't find any additional content via the developer tools, so I assume it's a minor bug :smile: .

**Comment by twifty** [comment]
A full description of the failure should be behind the expando.

**Comment by twifty** [comment]
@Gert-dev I can't seem to reproduce this. Is there any chance you could provide a junit.xml test report with such a failure?

**Comment by Gert-dev** [comment]
Hmm. This happened with a project at work, but I can't reproduce it with PHP Integrator's core.

I'll try again next week. if I can't reproduce it anymore, I'll close this.

**Comment by Gert-dev** [comment]
I tested this again and it no longer seems to occur. I'll close this.
