### ISSUE TITLE
Enable separation of components into own tabs

### ISSUE THREAD

**Issue by Gert-dev** [twifty/atom-phpunit-integrator#8]
It would be neat if the failed assertions could somehow be viewed via this package. PhpStorm, for example, allows showing tooltips (such as those provided by atom-ide-ui) with the failed assertions and PHPUnit failed assertion diffs in.

The PHPUnit raw console output is currently occupying a rather large portion of the dock. Whilst it is always useful to have handy for debugging, it could be hidden behind an additional button if its prime and most common use case, viewing failed assertions, could be replaced by a way to view them from the tests tree - be it via a tooltip, expando or something else.

**Comment by twifty** [comment]
You mentioned in #3 that the icons are not displaying. There should be a button there to filter the results in the tree. The assertation messages should also be expandable on the individual tree items.

The three individual panes can be resized by dragging the divider, the package will also remember the positions during reload. But, the ability to hide each pane would be useful.

**Comment by twifty** [comment]
@Gert-dev Thanks for the taking the time to test the package and especially for the feedback :+1:

**Comment by Gert-dev** [comment]
Thanks for taking the time to respond and you're very welcome.

I got #3 to work with another project and saw the failed assertions, which is exactly what I was looking for. Feel free to close this or keep it open for the pane. I could also create a separate ticket about it, if you want (or the issue title could be updated).

On the subject of hiding the raw output pane, I was just moving around the dock and noticed that, because all three panes are integrated into one single dock, it isn't very flexible in its location. For example, if you wanted it as a sidebar, it is very cramped in space.

A more interesting approach than allowing to hide the console might be to just split the three panes up into separate tabs (docks). That way the user can position them independently and just close any one of them he doesn't want - there should still be some way to reopen them, if closed, however. Positioning them next to each other is also still possible, this way.

**Comment by twifty** [comment]
I too noticed that moving the view to the sidebar is just ugly. I'm so used to my own environment layout that I never though about having the tree view in the sidebar. Individual tabs sounds like a good idea, I'm just not sure how to manage opening them. Keyboard shortcuts would work, but I feel atom is already overflowing with shortcuts, it's becoming difficult to avoid conflicts. I'll give this some thought.

**Comment by twifty** [comment]
I've enabled a vertical layout in 0.0.7 and plan to add buttons to toggle the terminal and coverage panels. I think this may be a better solution to multiple tabs.

**Comment by twifty** [comment]
v0.0.11 has improved vertical layout support. Also added the ability to toggle the terminal and coverage views on/off.

@Gert-dev Let me know if you think separate tabs would still be required.

**Comment by twifty** [comment]
I've got most (all) of the event system in place for #9 I just want to get this main component functioning correctly before I go adding further dependencies.

I left the coverage view in place since it also adds the ability to sort the files based on percentage and statements (un)covered, which I often use myself. While the tree view would be useful, in large projects it could be combersome to expand several folders just to find that one file with 98% coverage ;)
